package mscalc.ratpack;

import mscalc.cpp.uintArray;
import mscalc.ratpack.RatPack.NUMBER;

public interface RatConst {
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_num_one = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_num_two = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    2,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_num_five = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    5,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_num_six = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    6,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_num_ten = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    10,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_smallest = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    NUMBER init_q_rat_smallest = new NUMBER(1,
            4,
            0,
            new uintArray(new int[]{
                    0,
                    190439170,
                    901055854,
                    10097,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_negsmallest = new NUMBER(-1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    NUMBER init_q_rat_negsmallest = new NUMBER(1,
            4,
            0,
            new uintArray(new int[]{
                    0,
                    190439170,
                    901055854,
                    10097,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_pt_eight_five = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    85,
            }));
    NUMBER init_q_pt_eight_five = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    100,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_six = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    6,
            }));
    NUMBER init_q_rat_six = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_two = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    2,
            }));
    NUMBER init_q_rat_two = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_zero = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    0,
            }));
    NUMBER init_q_rat_zero = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_one = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    NUMBER init_q_rat_one = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_neg_one = new NUMBER(-1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    NUMBER init_q_rat_neg_one = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_half = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    NUMBER init_q_rat_half = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    2,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_ten = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    10,
            }));
    NUMBER init_q_rat_ten = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_pi = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    125527896,
                    283898350,
                    1960493936,
                    1672850762,
                    1288168272,
                    8,
            }));
    NUMBER init_q_pi = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1288380402,
                    1120116153,
                    1860424692,
                    1944118326,
                    1583591604,
                    2,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_two_pi = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    251055792,
                    567796700,
                    1773504224,
                    1198217877,
                    428852897,
                    17,
            }));
    NUMBER init_q_two_pi = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1288380402,
                    1120116153,
                    1860424692,
                    1944118326,
                    1583591604,
                    2,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_pi_over_two = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    125527896,
                    283898350,
                    1960493936,
                    1672850762,
                    1288168272,
                    8,
            }));
    NUMBER init_q_pi_over_two = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    429277156,
                    92748659,
                    1573365737,
                    1740753005,
                    1019699561,
                    5,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_one_pt_five_pi = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1241201312,
                    270061909,
                    1051574664,
                    1924965045,
                    1340320627,
                    70,
            }));
    NUMBER init_q_one_pt_five_pi = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1579671539,
                    1837970263,
                    1067644340,
                    523549916,
                    2119366659,
                    14,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_e_to_one_half = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    256945612,
                    216219427,
                    223516738,
                    477442596,
                    581063757,
                    23,
            }));
    NUMBER init_q_e_to_one_half = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1536828363,
                    698484484,
                    1127331835,
                    224219346,
                    245499408,
                    14,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_exp = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    943665199,
                    1606559160,
                    1094967530,
                    1759391384,
                    1671799163,
                    1123581,
            }));
    NUMBER init_q_rat_exp = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    879242208,
                    2022880100,
                    617392930,
                    1374929092,
                    1367479163,
                    413342,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_ln_ten = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    2086268922,
                    165794492,
                    1416063951,
                    1851428830,
                    1893239400,
                    65366841,
            }));
    NUMBER init_q_ln_ten = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    26790652,
                    564532679,
                    783998273,
                    216030448,
                    1564709968,
                    28388458,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_ln_two = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1789230241,
                    1057927868,
                    715399197,
                    908801241,
                    1411265331,
                    3,
            }));
    NUMBER init_q_ln_two = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    1559869847,
                    1930657510,
                    1228561531,
                    219003871,
                    593099283,
                    5,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rad_to_deg = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    2127722024,
                    1904928383,
                    2016479213,
                    2048947859,
                    1578647346,
                    492,
            }));
    NUMBER init_q_rad_to_deg = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    125527896,
                    283898350,
                    1960493936,
                    1672850762,
                    1288168272,
                    8,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rad_to_grad = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    2125526288,
                    684931327,
                    570267400,
                    129125085,
                    1038224725,
                    547,
            }));
    NUMBER init_q_rad_to_grad = new NUMBER(1,
            6,
            0,
            new uintArray(new int[]{
                    125527896,
                    283898350,
                    1960493936,
                    1672850762,
                    1288168272,
                    8,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_qword = new NUMBER(1,
            3,
            0,
            new uintArray(new int[]{
                    2147483647,
                    2147483647,
                    3,
            }));
    NUMBER init_q_rat_qword = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_dword = new NUMBER(1,
            2,
            0,
            new uintArray(new int[]{
                    2147483647,
                    1,
            }));
    NUMBER init_q_rat_dword = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_max_i32 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    2147483647,
            }));
    NUMBER init_q_rat_max_i32 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_min_i32 = new NUMBER(-1,
            2,
            0,
            new uintArray(new int[]{
                    0,
                    1,
            }));
    NUMBER init_q_rat_min_i32 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_word = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    65535,
            }));
    NUMBER init_q_rat_word = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_byte = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    255,
            }));
    NUMBER init_q_rat_byte = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_400 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    400,
            }));
    NUMBER init_q_rat_400 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_360 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    360,
            }));
    NUMBER init_q_rat_360 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_200 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    200,
            }));
    NUMBER init_q_rat_200 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_180 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    180,
            }));
    NUMBER init_q_rat_180 = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_max_exp = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    100000,
            }));
    NUMBER init_q_rat_max_exp = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_min_exp = new NUMBER(-1,
            1,
            0,
            new uintArray(new int[]{
                    100000,
            }));
    NUMBER init_q_rat_min_exp = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));

    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_max_fact = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    3249,
            }));
    NUMBER init_q_rat_max_fact = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));

    // Autogenerated by _dumprawrat in support.cpp
    NUMBER init_p_rat_min_fact = new NUMBER(-1,
            1,
            0,
            new uintArray(new int[]{
                    1000,
            }));
    NUMBER init_q_rat_min_fact = new NUMBER(1,
            1,
            0,
            new uintArray(new int[]{
                    1,
            }));
}
